[package]
name = "draw"
version = "0.2.1"
authors = ["Ryan Ragona <ryan@ragona.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ragona/draw"

[dependencies]
rgb = "0.8.14"
svg = "0.5.12"
cgmath = "0.17.0"
