[package]
name = "draw"
version = "0.1.0"
authors = ["ragona <ryanragona@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.4"
num-complex = "0.2.1"
lazy_static = "1.2.0"
itertools = "0.8"
bresenham = "0.1.1"
png = "0.14.0"
rayon = "1.0.3"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark_draw"
harness = false

[lib]
bench = false